openapi: 3.0.3
info:
  title: Stampchain - OpenAPI 3.0
  description: Stampchain API UI
  version: 2.0.0
externalDocs:
  description: Find out more about Stampchain
  url: 'http://stampchain.io'
servers:
  - url: 'https://stampchain.io'
    description:  Production server (uses live data)
  - url: "https://bitcoinstamps.xyz"
    description: Production server (uses live data)
  - url: 'http://localhost:8000'
  #   description: Development server (local)
  # - url: 'https://btcstamps.deno.dev/'
  #   description: Staging server (uses live data)
paths:


  /api/v2/balance/{address}:
    get:
      summary: Get balance by address
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
          description: The address of the wallet
      responses: 
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedBalanceResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/block/{block_index}:
    get:
      summary: Get block info by block index or block hash
      parameters:
        - in: path
          name: block_index
          required: true
          schema:
            type: string
          description: The block index or block hash
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockInfoResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/block/block_count/{number}:
    get:
      summary: Get last x blocks
      parameters:
        - in: path
          name: number
          required: true
          schema:
            type: integer
          description: The number of last blocks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockInfo'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/block/related/{block_index}:
    get:
      summary: Get related blocks by block index or block hash
      parameters:
        - in: path
          name: block_index
          required: true
          schema:
            type: string
          description: The block index or block hash
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockRelatedResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/cursed:
    get:
      summary: Get paginated cursed stamps
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: 'The maximum number of stamps to retrieve (default: 50)'
        - in: query
          name: page
          schema:
            type: integer
          description: 'The page number of the results (default: 0)'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStampResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/cursed/{id}:
    get:
      summary: Get stamp information by ID or identifier
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Stamp number, cpid, or stamp_hash
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/cursed/block/{block_index}:
    get:
      summary: Get cursed stamps by block index
      parameters:
        - in: path
          name: block_index
          required: true
          schema:
            type: integer
          description: The block index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampBlockResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'



  /api/v2/cursed/ident/{ident}:
    get:
      summary: Get paginated cursed stamps by ident
      parameters:
        - in: path
          name: ident
          required: true
          schema:
            type: string
          description: The ident of the stamp (SRC-721, STAMP)
        - in: query
          name: limit
          schema:
            type: integer
          description: 'The maximum number of stamps to retrieve (default: 50)'
        - in: query
          name: page
          schema:
            type: integer
          description: 'The page number of the results (default: 1)'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedIdResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/issuances/{id}:
    get:
      summary: Get stamp issuances by stamp number, cpid, or stamp_hash
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Stamp number, cpid, or stamp_hash
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampsResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/src20:
    get:
      summary: Get paginated valid src20 transactions
      description: Retrieve paginated valid src20 transactions with optional limit and page parameters
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 50
          description: The maximum number of transactions to retrieve per page
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: The page number of transactions to retrieve
      responses:
        '200':
          description: Successful response with paginated src20 transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSrc20ResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'



  /api/v2/src20/balance/{address}:
    get:
      summary: Get src20 balance by address
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
          description: The address of the wallet
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Src20BalanceResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/src20/balance/{address}/{tick}:
    get:
      summary: Get src20 balance by address and tick
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
          description: The address of the wallet
        - in: path
          name: tick
          required: true
          schema:
            type: string
          description: The tick value
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Src20BalanceResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/src20/balance/snapshot/{tick}:
    get:
      summary: | 
        Get src20 balance snapshot by tick, based upon current block height.
      description: |
        Retrieve a snapshot of all owners for the SRC-20 tick value based upon the current block height.
      parameters:
        - in: path
          name: tick
          required: true
          schema:
            type: string
          description: The SRC20 tick value
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 200
          description: The maximum number of transactions to retrieve per page
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: The page number of transactions to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Src20SnapshotResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/src20/block/{block_index}:
    get:
      summary: Get paginated valid src20 transactions from a specific block
      parameters:
        - in: path
          name: block_index
          required: true
          schema:
            type: integer
          description: The index of the block
        - in: query
          name: limit
          schema:
            type: integer
          description: 'The maximum number of transactions to retrieve (default: 50)'
        - in: query
          name: page
          schema:
            type: integer
          description: 'The page number of the results (default: 1)'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSrc20ResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'



  /api/v2/src20/block/{block_index}/{tick}:
    get:
      summary: Get valid src20 transactions from a specific block and tick.
      parameters:
        - in: path
          name: block_index
          required: true
          schema:
            type: string
          description: The index of the block.
        - in: path
          name: tick
          required: true
          schema:
            type: string
          description: The tick value.
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 50
          description: The maximum number of transactions to return per page.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: The page number.
      responses:
        '200':
          description: Successful response with the list of valid src20 transactions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSrc20ResponseBody'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/src20/tick:
    get:
      summary: Get paginated valid src20 transactions by operation type
      description: Retrieve paginated valid src20 transactions by operation type (DEPLOY)
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 50
          description: The maximum number of transactions to retrieve per page
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: The page number of transactions to retrieve
      responses:
        '200':
          description: Successful response with paginated src20 transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSrc20ResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'






  /api/v2/src20/tick/{tick}:
    get:
      summary: Get paginated tick data
      description: Retrieve paginated tick data for a specific tick
      parameters:
        - in: path
          name: tick
          required: true
          description: Tick value
          schema:
            type: string
        - in: query
          name: limit
          description: 'Number of records per page (default: 50)'
          schema:
            type: integer
        - in: query
          name: page
          description: 'Page number (default: 1)'
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTickResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
  /api/v2/src20/tick/{tick}/deploy:
    get:
      summary: Get deployment details for a specific tick
      description: Retrieve deployment details for a specific tick in the tick API.
      parameters:
        - in: path
          name: tick
          required: true
          description: The tick value.
          schema:
            type: string
      responses:
        '200':
          description: Successful response with deployment details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TickResponseBody'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/src20/tx/{tx_hash}:
    get:
      summary: Get information about a specific transaction.
      parameters:
        - in: path
          name: tx_hash
          required: true
          schema:
            type: string
          description: The hash of the transaction.
      responses:
        '200':
          description: Successful response with transaction information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Src20ResponseBody'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'





  /api/v2/stamps:
    get:
      summary: Get paginated stamps
      description: Retrieve a paginated list of stamps.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: The maximum number of stamps to return per page. Defaults to 50.
        - in: query
          name: page
          schema:
            type: integer
          description: The page number to retrieve. Defaults to 1.
      responses:
        '200':
          description: Successful response with paginated stamps.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStampResponseBody'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/stamps/{id}:
    get:
      summary: Get stamp by ID {tx_hash, stamp, cpid}
      description: Retrieve a stamp by its ID one of tx_hash, stamp number, or cpid
      parameters:
        - in: path
          name: id
          required: true
          description: ID {tx_hash, stamp, cpid} of the stamp
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


  /api/v2/stamps/balance/{address}:
    get:
      summary: Get stamp balances by address
      description: Retrieve stamp balances for a specific address
      parameters:
        - in: path
          name: address
          required: true
          description: The address to retrieve stamp balances for
          schema:
            type: string
        - in: query
          name: limit
          description: 'The maximum number of stamp balances to retrieve. default: 50'
          schema:
            type: integer
        - in: query
          name: page
          description: 'The page number of stamp balances to retrieve. default: 1'
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStampBalanceResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/stamps/block/{block_index}:
    get:
      summary: Get stamps by block index
      parameters:
        - in: path
          name: block_index
          required: true
          schema:
            type: string
          description: The index of the block
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampBlockResponseBody'
        '404':
          description: Block not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'



  /api/v2/stamps/ident/{ident}:
    get:
      summary: Get stamps by ident
      description: Retrieve stamps based on the provided ident
      parameters:
        - in: path
          name: ident
          required: true
          description: The ident value (SRC-721, STAMP)
          schema:
            type: string
        - in: query
          name: limit
          description: 'The maximum number of stamps to retrieve (default: 50)'
          schema:
            type: integer
        - in: query
          name: page
          description: 'The page number of stamps to retrieve (default: 1)'
          schema:
            type: integer
      responses:
        '200':
          description: Successful response with the paginated stamps
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedIdResponseBody'
        '404':
          description: Stamps with the provided ident not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/stamps/dispensers/{id}:
      get:
      summary: Get open dispensers by stamp number, cpid, or stamp_hash
      description: Retrieve open dispensers by stamp number, cpid, or stamp_hash
      parameters:
        - in: path
          name: id
          required: true
          description: Stamp number, cpid, or stamp_hash
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StampResponseBody'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /api/v2/src20/create:
    post:
      summary: Deploy, Mint, Transfer SRC-20 Tokens
      description: |
        This returns an unsigned transaction ready for signing and broadcasting
        via wallet or library. There is no validation that the input data provided
        will conform to SRC-20 specifications or mint limit requirements. It is the 
        users sole responsibility to confirm mint, deploy limits and confirm existing
        balances prior to a transfer of tokens. The examples provided are for demonstration
        purposes only.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputData'
            examples:
              deploy:
                value:
                  toAddress: "bc1ql49ydapnjafl5t2cp9zqpjwe6pdgmxy98859v2"
                  changeAddress: "bc1qazcm763858nkj2dj986etajv6wquslv8uxwczt"
                  op: "deploy"
                  tick: "KEVIN"
                  feeRate: 60
                  max: 2100000000
                  lim: 100000
                  dec: 18
              mint:
                value:
                  toAddress: "bc1ql49ydapnjafl5t2cp9zqpjwe6pdgmxy98859v2"
                  changeAddress: "bc1qazcm763858nkj2dj986etajv6wquslv8uxwczt"
                  op: "mint"
                  tick: "DOGE"
                  feeRate: 150
                  amt: 1000
              transfer:
                value:
                  fromAddress: "bc1qdnksce7dgfsehtdxgz6fzdj2k6qfvmyf8uc2vv"
                  toAddress: "bc1qazcm763858nkj2dj986etajv6wquslv8uxwczt"
                  op: "transfer"
                  tick: "STAMP"
                  feeRate: 150
                  amt: 100000
      responses:
        '200':
          description: Successful response with the hex value.
          content:
            application/json:
              schema:
                type: object
                properties:
                  hex:
                    type: string
                    description: The hex value.
        '400':
          description: Bad request error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message.

  /api/v2/olga/mint:
    post:
      summary: Mint an OLGA STAMP.
      description: |
        This returns an unsigned transaction ready for signing and broadcasting
        via wallet or library. There is no validation that the input data provided
        will conform to all STAMP specifications. It is the users sole responsibility 
        The examples provided are for demonstration purposes only.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MintStampInputData'
            examples:
              mint:
                value:
                  sourceWallet: "bc1ql49ydapnjafl5t2cp9zqpjwe6pdgmxy98859v2"
                  qty: 1
                  locked: true
                  divisible: true
                  filename: test.png
                  file: "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAG1BMVEUAAAALOzcKBiAJTzz/1lqZoxgIaSyfQuJmIslgvM+QAAAAAXRSTlMAQObYZgAAAMlJREFUeNp9kNVhAzEMQFVtYE+ge8HfxhsUFkjuFih4gPJ3Jz9mMPuJJVvjzkR0CBJf7CFQB05GKs75EVCwEbAa+3Wg9XmZ5rOz7gljoE9ZmSydzT67lqcdaWrhUCo8m8baKDEt7Qqz4wtVKTVHRI8R2N1bW7wqMb4GLya0KQOYVOUrXfIaHKWY1lsCTfKXyih0msQXeA1td/RoHGOk++8figPKo67o+dqappTnx8FakD2Vxf11QA78F+cZ6cC5BCrd0F+T8UDmIwdjIhoVAu1hnQAAAABJRU5ErkJggg=="
                  satsPerKB: 20
                  service_fee: null
                  service_fee_address: null
      responses:
        '200':
          description: Successful response with the hex value.
          content:
            application/json:
              schema:
                type: object
                properties:
                  hex:
                    type: string
                    description: The hex value.
        '400':
          description: Bad request error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message.
  

components:
  schemas:
    SUBPROTOCOLS:
      type: string
      enum:
        - STAMP
        - SRC-20
        - SRC-721
    BlockRow:
      type: object
      properties:
        block_index:
          type: number
        block_hash:
          type: string
        block_time:
          oneOf:
            - type: number
            - type: string
              format: date-time
        previous_block_hash:
          type: string
        difficulty:
          type: number
        ledger_hash:
          type: string
        txlist_hash:
          type: string
        messages_hash:
          type: string
        indexed:
          type: number
        issuances:
          type: number
        sends:
          type: number
    StampRow:
      type: object
      properties:
        stamp:
          oneOf:
            - type: number
            
        block_index:
          type: number
        cpid:
          type: string
            
        creator:
          type: string
        divisible:
          type: number
        keyburn:
          oneOf:
            - type: number
            
        locked:
          type: number
        stamp_base64:
          type: string
        stamp_mimetype:
          type: string
        stamp_url:
          type: string
        supply:
          type: number
        timestamp:
          type: string
          format: date-time
        tx_hash:
          type: string
        tx_index:
          type: number
        src_data:
          type: string
        ident:
          $ref: "#/components/schemas/SUBPROTOCOLS"
        creator_name:
          oneOf:
            - type: string
            
        stamp_gen:
          type: string
        stamp_hash:
          type: string
        is_btc_stamp:
          oneOf:
            - type: number
            
        file_hash:
          type: string
    SendRow:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        cpid:
          oneOf:
            - type: string
            
        tick:
          oneOf:
            - type: string
            
        memo:
          type: string
        quantity:
          type: string
          format: int64
        tx_hash:
          type: string
        tx_index:
          type: number
        block_index:
          type: number
    HolderRow:
      type: object
      properties:
        address:
          type: string
        quantity:
          type: number
        divisible:
          type: number
    BlockInfo:
      type: object
      properties:
        block_info:
          $ref: "#/components/schemas/BlockRow"
        issuances:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
        sends:
          type: array
          items:
            $ref: "#/components/schemas/SendRow"
    BtcInfo:
      type: object
      properties:
        address:
          type: string
        balance:
          type: number
        txCount:
          type: number
        unconfirmedBalance:
          type: number
        unconfirmedTxCount:
          type: number
    XCPParams:
      type: object
      properties:
        filters:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              op:
                type: string
              value:
                type: string
        address:
          type: string
        asset:
          type: string
    SRC20Balance:
      type: object
      properties:
        id:
          type: string
        address:
          type: string
        cpid:
          type: string
        p:
          type: string
        tick:
          type: string
        amt:
          type: number
        block_time:
          type: string
          format: date-time
        last_update:
          type: number
    Src20Detail:
      type: object
      properties:
        tx_hash:
          type: string
        tx_index:
          type: number
        block_index:
          type: number
        p:
          type: string
        op:
          type: string
        tick:
          type: string
        creator:
          type: string
        amt:
          oneOf:
            - type: number
        deci:
          type: number
        lim:
          type: string
        max:
          type: string
        destination:
          type: string
        block_time:
          type: string
        status:
          oneOf:
            - type: object
        creator_name:
          oneOf:
            - type: string
        destination_name:
          type: string
    Src20SnapshotDetail:
      type: object
      properties:
        tick:
          type: string
        address:
          type: string
        balance:
          oneOf:
            - type: number
            - type: string
    
    StampBalance:
      type: object
      properties:
        cpid:
          type: string
        stamp:
          type: number
        stamp_base64:
          type: string
        stamp_url:
          type: string
        stamp_mimetype:
          type: string
        tx_hash:
          type: string
        is_btc_stamp:
          oneOf:
            - type: number
            - type: boolean
        divisible:
          type: number
        supply:
          oneOf:
            - type: number
            - type: string
        locked:
          oneOf:
            - type: number
            - type: boolean
        creator:
          type: string
        creator_name:
          oneOf:
            - type: string
        balance:
          oneOf:
            - type: number
            - type: string
    MintStatus:
      type: object
      properties:
        max_supply:
          type: string
        total_minted:
          type: string
        total_mints:
          type: number
        progress:
          type: string
        decimals:
          type: number
        limit:
          oneOf:
            - type: number
            
    PaginationQueryParams:
      type: object
      properties:
        limit:
          type: number
        page:
          type: number
    PaginatedRequest:
      type: object
      properties:
        query:
          $ref: "#/components/schemas/PaginationQueryParams"
    Pagination:
      type: object
      properties:
        page:
          type: number
        limit:
          type: number
        totalPages:
          type: number
        total:
          type: number
    PaginatedStampResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampRow"
    PaginatedStampBalanceResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampBalance"
    PaginatedSrc20ResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            data:
              type: array
              items:
                $ref: "#/components/schemas/Src20Detail"
    PaginatedTickResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            mint_status:
              $ref: "#/components/schemas/MintStatus"
            data:
              type: array
              items:
                $ref: "#/components/schemas/Src20Detail"
    TickResponseBody:
      type: object
      properties:
        last_block:
          type: number
        mint_status:
          $ref: "#/components/schemas/MintStatus"
        data:
          $ref: "#/components/schemas/Src20Detail"
    Src20SnapshotResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            snapshot_block:
              type: number
            data:
              $ref: "#/components/schemas/Src20SnapshotDetail"
   
    StampsAndSrc20:
      type: object
      properties:
        stamps:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
        src20:
          type: array
          items:
            $ref: "#/components/schemas/SRC20Balance"
    Src20ResponseBody:
      type: object
      properties:
        last_block:
          type: number
        data:
          $ref: "#/components/schemas/Src20Detail"
    Src20BalanceResponseBody:
      type: object
      properties:
        last_block:
          type: number
        data:
          type: array
          items:
            $ref: "#/components/schemas/Src20Detail"
    PaginatedBalanceResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            btc:
              $ref: "#/components/schemas/BtcInfo"
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampsAndSrc20"
    StampResponseBody:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/StampRow"
        last_block:
          type: number
    StampsResponseBody:
      type: object
      properties:
        last_block:
          type: number
        data:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
    PaginatedIdResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            ident:
              oneOf:
                - type: string
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampRow"
    ErrorResponseBody:
      type: object
      properties:
        error:
          type: string
    PaginatedResponseBody:
      oneOf:
        - $ref: "#/components/schemas/PaginatedStampResponseBody"
        - $ref: "#/components/schemas/ErrorResponseBody"
    BlockInfoResponseBody:
      type: object
      properties:
        block_info:
          $ref: "#/components/schemas/BlockRow"
        issuances:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
        sends:
          type: array
          items:
            $ref: "#/components/schemas/SendRow"
        last_block:
          type: number
    BlockRelatedResponseBody:
      type: object
      properties:
        last_block:
          type: number
        blocks:
          type: array
          items:
            $ref: "#/components/schemas/BlockRow"
    StampBlockResponseBody:
      type: object
      properties:
        block_info:
          $ref: "#/components/schemas/BlockRow"
        data:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
        last_block:
          type: number
    IdHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            id:
              oneOf:
                - type: string
                - type: number
    IdentHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            ident:
              type: string
    BlockHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            block_index:
              oneOf:
                - type: number
                - type: string
    AddressHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            address:
              type: string
    TxHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            tx_hash:
              type: string
    TickHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            tick:
              oneOf:
                - type: string
                - type: number
    BlockTickHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            block_index:
              oneOf:
                - type: number
                - type: string
            tick:
              oneOf:
                - type: string
                - type: number
    AddressTickHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            address:
              type: string
            tick:
              oneOf:
                - type: string
                - type: number
    TX:
      type: object
      properties:
        hex:
          type: string
    TXError:
      type: object
      properties:
        error:
          type: string
    InputData:
      type: object
      properties:
        op:
          type: string
        toAddress:
          type: string
        changeAddress:
          type: string
        fromAddress:
          oneOf:
            - type: string
              nullable: true
        tick:
          type: string
        feeRate:
          type: number
        max:
          oneOf:
            - type: number
            - type: string
              nullable: true
        lim:
          oneOf:
            - type: number
            - type: string
              nullable: true
        dec:
          type: number
          nullable: true
        amt:
          oneOf:
            - type: number
            - type: string
              nullable: true
    MintStampInputData:
      type: object
      properties:
        sourceWallet:
          type: string
        assetName:
          oneOf:
            - type: string
            - type: undefined
        qty:
          type: number
        locked:
          type: boolean
        divisible:
          type: boolean
        filename:
          type: string
        file:
          type: string
        satsPerKB:
          type: number
        service_fee:
          oneOf:
            - type: number
            - type: undefined
        service_fee_address:
          oneOf:
            - type: string
            - type: undefined